plugins {
    id 'com.android.application'
}

android {
    namespace 'com.cue.simplebrowser'
    compileSdk 37
    compileSdkMinor 2

    defaultConfig {
        applicationId 'com.cue.simplebrowser'
        minSdk 29
        targetSdk 35
        versionCode 14
        versionName '2.5.0'
    }

    signingConfigs {
        debug {
            enableV3Signing true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    splits {
        abi {
            enable true
            reset()
            include 'arm64-v8a', 'x86_64'
            universalApk false
        }
    }

    buildTypes {
        debug {
            debuggable true
        }
        release {
            minifyEnabled false
            shrinkResources false
            signingConfig signingConfigs.debug
        }
    }
}

dependencies {
    implementation 'org.mozilla.geckoview:geckoview:157.0.20260924084938'
    implementation 'androidx.appcompat:appcompat:1.8.0'
    implementation 'androidx.core:core:1.19.1'
}
